[package]
name = "bevy-vfx-bag"
version = "0.2.1"
edition = "2024"
description = "An assorted bag of visual effects for Bevy"
categories = ["graphics", "game-development", "rendering"]
keywords = ["vfx", "graphics", "bevy", "gamedev", "wgsl"]
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/ParkSnoopy/bevy-vfx-bag"

exclude = [".github/", "scripts/"]

[features]

default = ["sdr"]

hdr = []
sdr = []

[dependencies]
bevy = { version = "0.19", default-features = false, features = [
    "bevy_asset",
    "bevy_render",
    "bevy_core_pipeline",
    "png",
    "tga",
] }

[dev-dependencies]
bevy = { version = "0.19", features = ["tga"] }
color-eyre = "0.6"
image = "0.25"
once_cell = "1"
